name: Enhancement
description: Improve existing behavior, UX, or performance.
title: "[Enhancement]: "
labels:
  - type:enhancement
body:
  - type: markdown
    attributes:
      value: |
        Use this form to refine an existing workflow or polish behavior without introducing a brand-new capability.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Outline the improvement in a few sentences.
      placeholder: Streamline shelf spacing inputs in the cabinet editor.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Outcome
      description: Describe the improved behavior users should experience after this enhancement ships.
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Provide observable checks or Given/When/Then scenarios that define done.
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior / Limitation
      description: Explain what currently happens and why it needs refinement.
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Observe Current Behavior
      description: Provide steps or scenarios highlighting today’s experience.
  - type: textarea
    id: technical_description
    attributes:
      label: Technical Notes
      description: Document constraints, invariants, or implementation considerations.
  - type: textarea
    id: proposed_solutions
    attributes:
      label: Proposed Solutions
      description: Sketch potential approaches or follow-ups to explore.
